import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AppInit from "@/components/app.init";

import ContextComponent from "@/components/context.component";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://pro.fontawesome.com/releases/v5.15.4/css/all.css"
          rel="stylesheet"
        />
      </head>
      <body className={inter.className}>
        <ContextComponent>
          <AppInit>
            <div className="bg-white dark:bg-gray-800 min-h-screen transition-all">
              <div className="container mx-auto py-8">{children}</div>
            </div>
          </AppInit>
        </ContextComponent>
      </body>
    </html>
  );
}
